### ISSUE TITLE
New bug auto bump csgolounge 

### ISSUE THREAD

**Issue by mocbuhtigsptth** [ncla/LoungeDestroyer#352]
Cant auto bump 40 minutes, auto bump 1 hours 10 minutes

LoungeDestroyer content script has started.. 1485848763972 inject.js:1
AUTOBET :: status Object {type: "autoBet", autoBetting: false, matchNum: 0, betData: Object, lastError: ""…} bet.js:20
THEMES :: Theme CSS string is empty true inject.js:56
Local storage loaded 1485848764819 inject.js:44
settings have been loaded in content script! 1485848764823 inject.js:47User

Mixed Content: The page at 'https://csgolounge.com/trade?t=217358807' was loaded over HTTPS, but requested an insecure image 'http://csgolounge.com/img/trash.png'. This content should also be served over HTTPS. trade?t=217358807:167
Mixed Content: The page at 'https://csgolounge.com/trade?t=217358807' was loaded over HTTPS, but requested an insecure image 'http://csgolounge.com/img/ban.png'. This content should also be served over HTTPS. trade?t=217358807:168
Mixed Content: The page at 'https://csgolounge.com/trade?t=217358807' was loaded over HTTPS, but requested an insecure image 'http://csgolounge.com/img/reply.png'. This content should also be served over HTTPS. trade?t=217358807:169
Mixed Content: The page at 'https://csgolounge.com/trade?t=217358807' was loaded over HTTPS, but requested an insecure image 'http://csgolounge.com/img/trash.png'. This content should also be served over HTTPS. trade?t=217358807:181
Mixed Content: The page at 'https://csgolounge.com/trade?t=217358807' was loaded over HTTPS, but requested an insecure image 'http://csgolounge.com/img/ban.png'. This content should also be served over HTTPS. trade?t=217358807:182
Mixed Content: The page at 'https://csgolounge.com/trade?t=217358807' was loaded over HTTPS, but requested an insecure image 'http://csgolounge.com/img/reply.png'. This content should also be served over HTTPS. trade?t=217358807:183

 jQuery.Deferred exception: $(...).live is not a function TypeError: $(...).live is not a function jquery-3.1.0.min.js:2
    at r.fn.init.search (https://csgolounge.com/script/livesearch.js?1474547257:50:13)
    at HTMLDocument.<anonymous> (https://csgolounge.com/trade?t=217358807:236:27)
    at j (https://code.jquery.com/jquery-3.1.0.min.js:2:29568)
    at k (https://code.jquery.com/jquery-3.1.0.min.js:2:29882) undefined
r.Deferred.exceptionHook @	jquery-3.1.0.min.js:2
K @ jquery-3.1.0.min.js:2	

Uncaught TypeError: $(...).live is not a function(…)jquery-3.1.0.min.js:2
search	@	livesearch.js?1474547257:50
(anonymous function)	@	trade?t=217358807:236
j	@	jquery-3.1.0.min.js:2
k	@	jquery-3.1.0.min.js:2

thank you for your attention

**Comment by Gasur** [comment]
It seems as if it was fixed in #351. Have you updated your extension?

**Comment by mocbuhtigsptth** [comment]
yes my friend, I have 0.9.5.1
